FROM node:20-bookworm as s1

MAINTAINER tcneko <tcneko@outlook.com>

WORKDIR /root/net_scan
COPY src/ /root/net_scan/
RUN npm install react react-dom next sharp tailwindcss postcss autoprefixer
RUN npx next telemetry disable \
    && npx next build

ENTRYPOINT [ "npx", "next", "start"]